#! /usr/bin/env bash

remote=git@github.com:pydoit/doit.git

echo \(1\) Listing current remotes:
git remote -v
echo

echo \(2\) Adding $remote
git remote add vendor $remote
echo

echo \(3\) Fetching vendor
git fetch vendor
echo

echo \(4\) Upgrade local upstream branch through the vendor
git checkout upstream
git merge vendor/master
echo

echo \(5\) Upgrade local master branch through local upstream branch
git checkout master
git merge --squash upstream
echo

